hefg_list = ['C1OC1', 'O1C(C1)C', 
    'C1CNC1', 'C1CN(C1)C',
    'OO',
    'N=[N+]=[N-]',
    'N1=CC=CO1', 'C1C=C(ON=1)C', 'O1N=C(C=C1)C', 'N1=CC(=CO1)C',
    'C#C',
    'N#C', 'C#N',
    'N(=O)=O', '[N+]([O-])=O', 'N(=O)O',
    'O=NO', 
    'N+]#N', 'N=N', 
    '[O-]Cl', '[O-]Br',
    'O=Cl(=O)[O-]', 'O=Cl(=O)(=O)[O-]',
    'I=O', '(OI2(O)=O)=O', 
    '[Li]', '[Mg]',
    'NN',
    '[O-][N+](=O)[O-]',
    'NO',
    '[N+]', '[O-]',
    'C1N(CC1)']